### ISSUE TITLE
Project 2

### ISSUE THREAD

**Issue by johnlusher** [CourseReps/ECEN489-Spring2016#7] opened 2016-03-19 15:49 UTC
I have committed a draft version of the Maps Fragment to get the ball rolling on integration on the maps interface.  There will be many changes and updates as we integrate and get all the classes on the same page.  The classes of interest are:

MapsActivity.java:  Maps Fragment
RFFieldSQLDatabase.java: SQL Database Interface
LatLong.java: Simple Lat/Long Tool Set
RFData.java:  RF Data class being used for now, will be changed to match how we want the data to look

I am using a SQL database (MySQL) for now.  Fusion Table authentication on Android become too much of a pain for this project and Dr. Huff said we can catch that on the next version.  We will work on integrating this into the project and getting the loose ends tied up on Monday.

I will be early to class on Monday to work on it.  However, I will have to leave at 3:45 pm to get over to a research meeting in which I am presenting.

If you have any questions please let me know,

John
john.lusher@tamu.edu

**Comment by paulcrouther** [comment] 2016-03-21 06:11
I've also committed some UX changes. There's room for the "alignment" and the "maps" fragments.

Let me know if anyone has trouble.

**Comment by tbranyon** [comment] 2016-03-22 17:33
So the "MapsFragment" version of the project, is that a newer version of Kyle's "Project2" commit or are they separate parallel branches?

**Comment by johnlusher** [comment] 2016-03-22 17:59
This my Kyles's Project 2 that I had hacked.  I didn't want to cause any issues with updating the code that someone may have been working on so I just put in a separate area to be referenced.  

John

**Comment by samshore** [comment] 2016-03-22 18:18
I integrated the orientation graphic with the main project, for the most part. I was having trouble accessing the theta and phi values from the preference file though. If someone knows how to do this, I'd appreciate it if you could look at what I was trying to do. Right now the two lines that were causing a crash are just commented out. I was trying to use the values in the main fragment in the onSensorChanged method.

**Comment by Fanchao92** [comment] 2016-03-22 18:38
Can you try to first get the string, and then convert it into a double by
using:
Double.parseDouble()
?

2016年3月22日星期二，Sam Shore <notifications@github.com> 写道：

**Comment by samshore** [comment] 2016-03-22 22:01
Ok I think I found what the error was. I thought I had changed the default value to a number, but it is still "Angle1". Is there anywhere that defines the default preferences besides pref_general.xml?

**Comment by samshore** [comment] 2016-03-22 22:20
Never mind. I just had to uninstall and reinstall the app and then everything worked fine. So the orientation graphic is fully integrated now.

**Comment by tbranyon** [comment] 2016-03-22 23:01
So it looks like the settings can be communicated between the Settings fragment and the MainFragment via XML values. Is that an accurate interpretation?
And do any fragments/activities outside the Main Fragment need access to the live data (not the local db)?

**Comment by Fanchao92** [comment] 2016-03-22 23:06
I guess I do. Because I am now writing the code for starting another thread
and pushing data into the distant database, I may need to get the live data.

2016年3月22日星期二，Thomas Branyon <notifications@github.com> 写道：

**Comment by tbranyon** [comment] 2016-03-22 23:12
Ok. I think I'll change my class to hold just data members, rather than also containing the settings, since those are already handled via XML. If your thread creates an instance of my DataCollector class, it can access live data by using the public static members of DataCollector. Does that work for you?

**Comment by Fanchao92** [comment] 2016-03-22 23:21
Sure. That would be good. Thanks.

2016年3月22日星期二，Thomas Branyon <notifications@github.com> 写道：

**Comment by Fanchao92** [comment] 2016-03-22 23:25
Actually, I am thinking if it's better for me to later paste my code into
your thread, right below the data collection part. So we will have only one
neat piece of code, and collect and push data at one time.

2016年3月22日星期二，Fanchao Zhou <fanchaozhou1992@gmail.com> 写道：

**Comment by tbranyon** [comment] 2016-03-22 23:28
That would work even better actually. Go ahead.

**Comment by tbranyon** [comment] 2016-03-22 23:59
Fanchao, isn't the push to server already accomplished in a separate thread in the MainFragment? In the button click handler for the send data button, it launches that sendHTTPData routine in a separate thread. Or were you talking about something else/cleaning that up?

**Comment by Fanchao92** [comment] 2016-03-23 00:11
Yes, the data pushing is accomplished by you in MainFragment by a thread. But that's for the collection-on-click mode, and that's pushing data to the local SQLite database. Now I am writing a thread to push data to John's distant SQL database in the continuous data collection mode. It's a trivial work, because John has already written the class for me to push data. But someone still has to do it. And, we may add some code to the thread you wrote  in project 1, so it also pushes to John's SQL database(or later the Fusion Tables) in the collection-on-click mode as well.

**Comment by tbranyon** [comment] 2016-03-23 00:16
My original code was configured to push to a tomcat server. Sam did the local db stuff. Either way though, it may not be compatible with John's stuff.

Other things:
1) Java code in an Activity can't edit XML values right? Just realized I probably do need to store settings in the DataCollector class after all, so the MainFragment can access whatever changes the user makes to the default settings (assuming those changes can't be written back to XML). Thoughts?

2) Sam, not sure what happened with your commit, but since you made that XML-related change, the app crashes for me on opening, reporting an exception on your line that pulls the preference from XML, saying something about a null object. Can you verify that the app runs properly for you?

**Comment by samshore** [comment] 2016-03-23 00:19
Yeah it's crashing for me too now. I had everything working and pushed it. Then I came back later and did a pull and tried to run it and it crashed. I'll try to figure out what happened.

**Comment by tbranyon** [comment] 2016-03-23 00:21
Ah. Maybe I broke it...?

**Comment by samshore** [comment] 2016-03-23 00:29
I'm not sure. The changes I made in the pref_general.xml file were only changing default values to numbers instead of words, so that shouldn't hurt anything. I also tried commenting out everything I did in the main fragment, and it still crashes. So I'm not sure what the problem is. Are you getting the "Fatal signal 6 (SIGABRT)"?

**Comment by tbranyon** [comment] 2016-03-23 00:32
Sorry for the terrible formatting:

03-22 19:04:56.393 1862-1862/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.example.fanchaozhou.project1, PID: 1862
                                                 java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String android.content.SharedPreferences.getString(java.lang.String, java.lang.String)' on a null object reference
                                                     at com.example.fanchaozhou.project1.MainFragment.onSensorChanged(MainFragment.java:224)
                                                     at android.hardware.SystemSensorManager$SensorEventQueue.dispatchSensorEvent(SystemSensorManager.java:504)
                                                     at android.os.MessageQueue.nativePollOnce(Native Method)
                                                     at android.os.MessageQueue.next(MessageQueue.java:143)
                                                     at android.os.Looper.loop(Looper.java:130)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6938)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by samshore** [comment] 2016-03-23 00:37
Oh yeah that's my part! That was just working though so I'm not sure what changed. That's where I get the preferences for the theta and phi tolerances. But I think that's saying the value is null. I'm not sure why. I can comment it out for now until I figure out how to fix it.

**Comment by tbranyon** [comment] 2016-03-23 00:39
Yeah...weird. I don't see anything in your code that looks like it would cause an issue. I wouldn't think that any of my code would effect it either since I'm not touching any XML at the moment...

**Comment by samshore** [comment] 2016-03-23 00:40
Yeah I have no idea why that's happening now. I commented out the lines causing the crash. I also don't know why my log didn't have all of that.

**Comment by samshore** [comment] 2016-03-23 01:51
Ok I fixed the crash problem finally. Everything should be good now.

**Comment by Fanchao92** [comment] 2016-03-23 02:50
I've added a new SharedPreferences file, so when the app is closed and reopened, the previous settings on the MainFragment will be restored. Also, the settings on the MainFragment, such as the checkbox for alignment, are accessible everywhere in the app. But my emulator doesn't work with our new version of project 2, so I've no idea if it works as expected.

**Comment by tbranyon** [comment] 2016-03-23 02:59
Causing the following error on my phone:

java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.app.Activity.getSharedPreferences(java.lang.String, int)' on a null object reference
                                                                                      at com.example.fanchaozhou.project1.MainFragment.<init>(MainFragment.java:107)
                                                                                      at com.example.fanchaozhou.project1.MainActivity.onCreate(MainActivity.java:53)

**Comment by tbranyon** [comment] 2016-03-23 03:05
Can someone refresh me on the functionality of the "run" button? It currently has no click handler. I was thinking that once clicked, it should start a thread that continuously updates data (basically like running the "refresh button" routine in a loop) and pushes it to the local DB. Would that be acceptable?

**Comment by paulcrouther** [comment] 2016-03-23 03:18
Yes, that's the functionality that it's supposed to have. I'm going to
change it to a checkbox - right now just trying to get all of these changes
synced in my local copy.

**Comment by tbranyon** [comment] 2016-03-23 03:20
Oops...I just wrote a button click handler. I can just change it to respond to the new UI element instead though.

**Comment by paulcrouther** [comment] 2016-03-23 03:26
If you've already done that it's fine, as long as it works at this point.
I'll keep it as is for now.

**Comment by tbranyon** [comment] 2016-03-23 03:44
Fanchao, I fixed one of the null object exceptions (moved the SharedPreferences stuff to onCreate() instead of the constructor). It's still throwing another one due to the checkbox handler for alignment. Do you think it would fix the problem/make sense to put the code for that handler inside the AlignmentFragment class? I'm not sure that that will do anything or even work, but that CheckBox is a member of that Fragment, not the MainFragment...

**Comment by Fanchao92** [comment] 2016-03-23 03:47
Oh, yes, glad you noticed this. I didn't quite pay attention to where the
checkbox was.

2016年3月22日星期二，Thomas Branyon <notifications@github.com> 写道：

**Comment by Fanchao92** [comment] 2016-03-23 03:48
I used a sharedpreference file because I found it easier to access the
values of the settings in this way when I was writing the thread.

2016年3月22日星期二，Thomas Branyon <notifications@github.com> 写道：

**Comment by tbranyon** [comment] 2016-03-23 05:19
## Current State - 12:20AM, 23 March

App will build and run again now.

### What works:
<li> Pressing refresh takes one data point
<li> Pressing Run/Stop starts collecting data at 1hz, pressing it again stops
<li> Pressing Connect to Server launches the routine to sync with the remote server DB
<li> Alignment indicator
<li> Pressing Clear removes all current local data (might be an issue actually)
<li> Settings screen stores preferences and these persist across a Create/Destroy cycle

### What doesn't work:
<li> Magnetometer readings are taken but not actually used anywhere
<li> Maps fragment has not been integrated into the main project (Hoping to fix this in just a minute)
<li> Dynamic logging. All variables are currently recorded and displayed regardless of settings.
<li> Data rejection when orientation is out of tolerance (not implemented)
<li> Exiting the application throws an exception due to an unexplored issue in MainFragment.onDestroy()

### Unknown:
<li> Reading RxID, TxID, and RSSI over USB has not been tested in the most recent app version, but looks like it should work
<li> Settings screen lists a "compass" option separate from magnetometer and gyro. Not sure what this corresponds to, but it is currently not handled in data collection.


I'm sure there are more things for each section but that's all that I'm currently aware of.

**Comment by johnlusher** [comment] 2016-03-23 12:07
I have integrated in the MapView Fragment and have committed it to the repo.  Now, we need to integrate in the "SaveRFData" class that I wrote in the bottom of the MapView Fragment to where you will be recording the data to the server.  Just copy this AsyncTask to the class that you will do this and then run the task when you need to add data to the SQL server.

**Comment by johnlusher** [comment] 2016-03-23 13:45
I added in support for the onMapClick listener which will enable a user to click on a region in the map and update the heatmap.

**Comment by tbranyon** [comment] 2016-03-23 13:56
Awesome, thanks. I'll try to hit it again when I get to campus in a little bit.

**Comment by tbranyon** [comment] 2016-03-23 16:20
Done. Still need to iterate through all new entries in the local db (right now it just sends the most recent line when you click "Connect to server"), but it looks like it works.

As a side note, pressing the hardware "back" button on both the Maps and Settings screens crashes the app for me. Kind of low priority at the moment with so many other things broken but if someone wants to tackle that, go for it.

**Comment by tbranyon** [comment] 2016-03-23 16:51
Ok, it should iterate now. I modified RFData (perhaps a bit recklessly) to make it happen. Clicking send doesn't show any output in the Android monitor now though, so I'm not actually sure if I'm sending properly or not. It doesn't crash the app though at least. If someone has time before class, maybe take a look?

**Comment by johnlusher** [comment] 2016-03-23 17:10
I'll be able to look at it in about 30 min.

John

**Comment by captjacksparrowz** [comment] 2016-03-23 17:22
If anyone needs help integrating their parts, i am in the eic now until class working on this project.

**Closed** 2016-03-23 21:32 UTC
